on:
  repository_dispatch:
    types: [rocm-ci]

env:
  SOURCE_REPO_OWNER: 'kmaehashi'  # XXX
  SOURCE_REPO_NAME: 'test-repo-dispatch'  # XXX

jobs:
  test:
    runs-on: ubuntu-latest  # XXX
    steps:
    - name: 'Update Commit Status (Pending)'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: process.env.SOURCE_REPO_OWNER,
            repo: process.env.SOURCE_REPO_NAME,
            sha: inputs.sha,
            state: 'pending',
            context: inputs.action,
            description: 'In progress'
          })

    - name: 'Checkout'
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - run: sleep 300

    - name: 'Update Commit Status (Success)'
      uses: actions/github-script@v7
      if: success()
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: process.env.SOURCE_REPO_OWNER,
            repo: process.env.SOURCE_REPO_NAME,
            sha: inputs.sha,
            state: 'success',
            context: inputs.action,
            description: 'Successful'
          })

    - name: 'Update Commit Status (Failure)'
      uses: actions/github-script@v7
      if: failure()
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: process.env.SOURCE_REPO_OWNER,
            repo: process.env.SOURCE_REPO_NAME,
            sha: inputs.sha,
            state: 'failure',
            context: inputs.action,
            description: 'Failed'
          })
